menubar: false
toolbar:
  - formatselect | bold italic underline | alignleft aligncenter alignright alignjustify | numlist bullist outdent indent | undo redo
block_formats: "Paragraph=p;Header 1=h1;Header 2=h2;Header 3=h3"


